name: Deploy Convio_Node_API PROD

on:
  push:
    branches:
      - main
    paths:
      - convio-chatbot/**      

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
     convio-chatbot: ${{ steps.filter.outputs.convio-chatbot }}
            
    # For pull requests it's not necessary to checkout the code
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            convio-chatbot:
              - 'convio-chatbot/**'

  
    # JOB to build convio-chatbot code
  convio-chatbot:
    needs: changes
    if: ${{ needs.changes.outputs.convio-chatbot == 'true' }}
    name: Build and Deploy convio-chatbot lambda
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless AWS Authentication
        run: sls config credentials --provider aws --key AKIAYSWL5QZRSFZOW2HJ --secret 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
      - name: Build convio-chatbot lambda
        run: cd convio-chatbot && npm install
      - name: Deploy convio-chatbot API
        run: cd convio-chatbot && sls plugin install -n serverless-prune-plugin && sls plugin install -n serverless-plugin-ifelse && sls deploy --region eu-west-2 --stage dev

  
